eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    ip-address: ${spring.cloud.client.ipAddress}
    appname: service-consumer-feign #swaggerui 集成时会遇到的问题    写appname后不会有 还没测试 待验证
    instance-id: ${spring.application.name}:${spring.cloud.client.ipAddress}:${server.port}
    status-page-url: http://localhost:${server.port}/swagger-ui.html #默认是 http://localhost:${server.port}/info
server:
  port: 8765
spring:
  application:
    name: service-consumer-feign
