eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
      prefer-ip-address: true
      ip-address: ${spring.cloud.client.ipAddress}
      appname: service-zuul
      instance-id: ${spring.application.name}:${spring.cloud.client.ipAddress}:${server.port}
server:
  port: 8770
spring:
  application:
    name: service-zuul
  sleuth:
    sampler:
      percentage: 1
    web:
      skip-pattern: /api/applications|/api|health|/info|/health/|/health|/info/|info  # sleuth 不会收集 匹配的路径
  rabbitmq:
        host: 172.18.21.189
        port: 5672
        username: admin
        password: admin
zuul:
  routes:
    api-a:
      path: /api-a/**
      serviceId: service-consumer-ribbon
    api-b:
      path: /api-b/**
      serviceId: service-consumer-feign
management:
  security:
#  设为false后/health能拿到更多信息
    enabled: false