server:
  port: 8790
spring:
  application:
    name: zipkin-server
  sleuth:
    enabled: false
  rabbitmq:
    host: 172.18.21.189
    port: 5672
    username: admin
    password: admin

zipkin:
  storage:
    type: elasticsearch
    elasticsearch:
      cluster: elasticsearch
      hosts: 172.18.21.140:9200/ #127.0.0.1:9200
      index: zipkin
      index-shards: 5
      index-replicas: 1

      timeout: 10000





eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    ip-address: ${spring.cloud.client.ipAddress}
    appname: zipkin-server #swaggerui 集成时会遇到的问题    写appname后不会有 还没测试 待验证
    instance-id: ${spring.application.name}:${spring.cloud.client.ipAddress}:${server.port}

#   定期通知eureka server还活着 rennew  默认30s
#    lease-renewal-interval-in-seconds: 30



