eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    ip-address: ${spring.cloud.client.ipAddress}
    appname: service-consumer-ribbon #swaggerui 集成时会遇到的问题    写appname后不会有 还没测试 待验证
    instance-id: ${spring.application.name}:${spring.cloud.client.ipAddress}:${server.port}
    status-page-url: http://localhost:${server.port}/swagger-ui.html #默认是 http://localhost:${server.port}/info
server:
  port: 8764
spring:
  application:
    name: service-consumer-ribbon
#  zipkin:
#    base-url: http://localhost:8790
#    enabled: true
   #让 zipkin收集数据更及时
  sleuth:
    sampler:
      percentage: 1
    web:
      skip-pattern: health|/info|/health/|/health|/info/|info
  rabbitmq:
        host: 172.18.21.189
        port: 5672
        username: admin
        password: admin
  cloud:
    loadbalancer:
      retry:
        #启动resttemplate 失败重试机制 引入spring retry
        enabled: false

management:
  security:
#  设为false后/health能拿到更多信息
    enabled: false

hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 7000  # 执行超过7s hystrix command 起作用  如果直接让被调用的服务停掉 又没起作用

#spring.boot.admin.url: http://localhost:8769




