#http://localhost:8001/rmq/dev/master  可以通过这个地址 看到从git上拉下来的文件
server:
  port: 8001
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    ip-address: ${spring.cloud.client.ipAddress}
    appname: config-server #swaggerui 集成时会遇到的问题    写appname后不会有 还没测试 待验证
    instance-id: ${spring.application.name}:${spring.cloud.client.ipAddress}:${server.port}

#   定期通知eureka server还活着 rennew  默认30s
#    lease-renewal-interval-in-seconds: 30


spring:
  cloud:
    config:
      server:
        git:
          uri: http://172.18.21.106/WingOnTravels/ConfigServer.git # 配置gitlab仓库的地址，注意，此处必须以.git结尾
#          search-paths: /ConfigServer          # gitlab仓库地址下的相对地址，可以配置多个，用,分割。  测试的时候文件在根目录下
          username: huang_b                                              # gitlab仓库的账号
          password: Yuihjknm,123                                         # gitlab仓库的密码
          basedir: /gitconfigserver                                        # 这个是 git 目录  linux默认定期会去清理temp文件夹
#          clone-on-start: true                                           # 启动的时候去clone  发现有超时的问题
  rabbitmq:
        host: 172.18.21.189
        port: 5672
        username: admin
        password: admin
  application:
    name: config-server
    index: ${random.int}  # 避免同一个服务部署多个实例 刷新配置的时候 不会刷新的情况
management:
  security:
    enabled: false
#spring.boot.admin.url: http://localhost:8769
